name: remove labels

on:
  pull_request:
    types:
      - closed

jobs:
  remove-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: andymckay/labeler@master
        with:
          remove-labels: 'work in progress,ready for review,review in progress,needs revision'
